### ISSUE TITLE
Erro ao excluir convênio

### ISSUE THREAD

**Issue by RicardoBucard** [diogosmendonca/sisgee#30]
Ao excluir um convênio do sistema, este retorna para a página inicial e apresenta mensagem de sucesso na exclusão, porém se for feita a busca do convênio, ele continua salvo e o convênio continua persistido no BD, pois após tentarmos excluir um convênio, fomos salvar um novo com os dados certos naquele mesmo número e o sistema apontou que já existia um convênio salvo com aquele número

**Comment by RicardoBucard** [comment]
Mensagem de Erro ao tentar excluir
ERROR	2019-09-27 10:05:50,873	br.cefetrj.sisgee.view.convenio.ExcluirConvenioServlet	[http-nio-80-exec-5]	Exception ao tentar Excluir o Convenio
java.lang.NullPointerException
	at br.cefetrj.sisgee.control.ConvenioServices.excluirConvenio(ConvenioServices.java:201)
	at br.cefetrj.sisgee.view.convenio.ExcluirConvenioServlet.doGet(ExcluirConvenioServlet.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at br.cefetrj.sisgee.view.filters.TodasRequisicoesFilter.doFilter(TodasRequisicoesFilter.java:37)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:607)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

A linha 67 do excluirConvenioServlet é ConvenioServices.excluirConvenio(convenio, empresa, pessoa);
E a linha 201 do Convenio Services é a última do bloco a seguir:
 public static void excluirConvenio(Convenio convenio, Empresa empresa, Pessoa pessoa) throws Exception {

        GenericDAO<Convenio> convenioDao = PersistenceManager.createGenericDAO(Convenio.class);
        GenericDAO<Empresa> empresaDao = PersistenceManager.createGenericDAO(Empresa.class);
        GenericDAO<Pessoa> pessoaDao = PersistenceManager.createGenericDAO(Pessoa.class);
         System.out.println(convenio.getTermoEstagio());
          System.out.println(convenio.getTermoEstagios());
        if (convenio.getTermoEstagios() != null && convenio.getTermoEstagio().size() >= 1) {
            System.out.println("Existe Termo de Estagio");
            throw new Exception();

**Comment by RicardoBucard** [comment]
No console, a saída foi essa:
java.lang.IllegalArgumentException: Removing a detached instance br.cefetrj.sisgee.model.entity.Pessoa#45155
	at org.hibernate.jpa.event.internal.core.JpaDeleteEventListener.performDetachedEntityDeletionCheck(JpaDeleteEventListener.java:52)
	at org.hibernate.event.internal.DefaultDeleteEventListener.onDelete(DefaultDeleteEventListener.java:89)
	at org.hibernate.event.internal.DefaultDeleteEventListener.onDelete(DefaultDeleteEventListener.java:56)
	at org.hibernate.internal.SessionImpl.fireDelete(SessionImpl.java:984)
	at org.hibernate.internal.SessionImpl.delete(SessionImpl.java:920)
	at org.hibernate.internal.SessionImpl.remove(SessionImpl.java:3341)
	at br.cefetrj.sisgee.model.dao.GenericDAO.excluir(GenericDAO.java:75)
	at br.cefetrj.sisgee.control.ConvenioServices.excluirConvenio(ConvenioServices.java:221)
	at br.cefetrj.sisgee.view.convenio.ExcluirConvenioServlet.doGet(ExcluirConvenioServlet.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at br.cefetrj.sisgee.view.filters.TodasRequisicoesFilter.doFilter(TodasRequisicoesFilter.java:37)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:607)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Exclusão de Convênio concluída com sucesso.
